# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f354142d4b459becf93eab5c51faa276dea56eae0ccf9e25b8311ca2f0f66efa9dd1e1c045b9c4645f1d66469cf7f2df0f8599d2c5febda76a6113af946d6a51

test:
  secret_key_base: 978823927754ba37b746d1798d597040c9cfe214bbdb25292d7647c20aa072c49d68a09dfbdf37e436f3a1c2bac5a415511e706dac2e53387fa7e511e779c74c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
